# Generated by Django 3.2 on 2024-12-01 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField()),
                ('numero', models.CharField(max_length=20)),
                ('cantidad_bidones', models.PositiveIntegerField()),
            ],
        ),
    ]
